### ISSUE TITLE
Wordstar saves only to drive A -- Possibly not a WS issue

### ISSUE THREAD

**Issue by wd5gnr** [ivanizag/iz-cpm#1]
I haven't run it down yet, but for some reason WordStar always saves to drive a: -- could be disk handling or could be some problem with the WS configuration. Try this:

```
../../target/debug/iz-cpm --disk-a . --disk-b ../wordstar33 --disk-c ../zork --disk-d ..
b:
ws
N        (new non document)
B:TEST.TXT     (or just TEST.TXT)
Anything        (type anything)
^KX
```

The file TEST.TXT will now be on A:  Even stranger, it tries to read from B. So if you do a ^KS instead of ^KX the file will be saved but it will reread from B where the file is blank. The same thing happens on other drives. The save winds up on A and the reread comes from the drive you intended. So if you save to drive A it works fine. Any other drive, no.

A related problem is a side effect. If you are testing and do ^KS to save, your file goes blank (because it saves to A and rereads from B). If you now save again (say a ^KX to get out), you will write a blank file over your original file on A so now when you type the file on drive A it will be blank. Not really a bug because it would not happen if the reread were picking up the file which it would if the save had occurred on that drive.

I'll let you know if I find anything else out. This is on a clone of the repo, by the way. I have not tried it with the release version.

**Comment by wd5gnr** [comment]
ED appears to have the same behavior.

**Comment by ivanizag** [comment]
I can reproduce with your instructtions.

There is an issue with the rename BDOS call. Wordstar saves the file to "B:TEST.$$$" and then renames it to "B:TEST.TXT". The way fs.rename() in Rust works, the destination needs the full path. If none is given, the file is moved to the current (host) directory.

I will commit a fix.

Thank you for the report.

**Comment by wd5gnr** [comment]
Thanks!

**Comment by wd5gnr** [comment]
Tested.. Works great.

**Comment by ivanizag** [comment]
Thank you for verifying the fix.
