### ISSUE TITLE
the file commander dont work

### ISSUE THREAD

**Issue by dddfffggg777** [ivanizag/iz-cpm#10]
http://www.ac1-info.de/galerie/poppe_heiko/fc08.zip
![image](https://user-images.githubusercontent.com/114140927/210094366-f1ee8d20-a771-49bc-86b5-a11781ccd751.png)

**Comment by ivanizag** [comment]
That is expected. iz-cpm aim is to re-implement CP/M at the BDOS level on top of a modern OS. The BIOS, specially the block level access to the disks, is not emulated. There are no CP/M disk structures being used.

BIOS command 9 is SELDSK to select a physical disk and retrieve the Disk Parameter Header. There is no such thing on iz-cpm.
