### ISSUE TITLE
Compute File Size is incorrect

### ISSUE THREAD

**Issue by alank2** [ivanizag/iz-cpm#11]
Hi,

File size -> It returns -> What it should return
(wrong) 0 bytes -> 1 record -> 0 records
(correct) 1 byte -> 1 record -> 1 record (correct)
(correct) 127 bytes -> 1 record -> 1 record (correct)
(wrong) 128 bytes -> 3 records -> 1 records
(wrong) 129 bytes -> 3 records -> 2 records
(wrong) 255 bytes -> 3 records -> 2 records
(wrong) 256 bytes -> 4 records -> 2 records
(wrong) 257 bytes -> 4 records -> 3 records

I looked at the function and it looks like it adds 1 twice for some reason, but It should only add a 1 a single time and then only if the filesize % RECORD_SIZE is non-zero (% being a modulus operator).

**Comment by ivanizag** [comment]
Right, it doesn't seem correct. How have you tests? Did you campare the results to the actual CPM 2.2 implementation by Digital Research?

**Comment by alank2** [comment]
>Right, it doesn't seem correct. How have you tested? 

Yes.  I've been writing some file functions that read and write in blocks in CP/M.

>Did you compare the results with the actual CPM 2.2 implementation by Digital Research?

Yes.  I have a test program that works in CP/M 2.2 and also the CP/M player emulator.

The problem is just this one function computer file size.  I can look at it and suggest a fix if you want.

**Comment by ivanizag** [comment]
You are very welcome to send a PR. I don't have the time now to do and test the fix. If you do, I will gladly review the change and accept the contribution.

**Comment by alank2** [comment]
I'm not familiar with rust,  but I think the big problem is that the test for a non-aligned sector is using the wrong variable to compare against.  I'm not sure why the second record+=1 is there, I don't think it should be.

fn compute_file_size_internal(env: &mut BdosEnvironment, fcb: &Fcb) -> io::Result<u32> {
    let paths = find_host_files(env, fcb, false, false)?;
    let os_file = fs::File::open(&paths[0])?;

    let file_size = os_file.metadata()?.len();
    let mut record = file_size / RECORD_SIZE as u64;
REMOVE    if record % RECORD_SIZE as u64 != 0 {
ADD       if file_size % RECORD_SIZE as u64 != 0 {
        // We need integer division rounding up.
        record += 1;
    }

REMOVE    record += 1;
    if record >= 65536 {
        record = 65536;
    }
    Ok(record as u32)
}

**Comment by ivanizag** [comment]
I applied your fix. My code was very wrong. I don't know how it ended there.

Thanks!!

**Comment by alank2** [comment]
>I applied your fix. 

Awseome; I will test it out when I can.

>My code was very wrong. I don't know how it ended there.

We've all been there!

**Comment by alank2** [comment]
Can you do a new build for Windows and I'll test the changes?

**Comment by ivanizag** [comment]
Sure, once I am be back at home next week I will do the build.

**Comment by alank2** [comment]
Many thanks!!  Let me know when it is ready and I'll test it!

**Comment by alank2** [comment]
Hi Iván,

 

I won’t be able to test it for a couple of days – one question – why it is so much smaller in size?  The previous version iz-cpm.exe is 6052580 bytes, but this one is only 957440 bytes.

 

Thanks for the help!

 

I’ll let you know as soon as I test it.

 

Alan

**Comment by ivanizag** [comment]
> why it is so much smaller in size? The previous version iz-cpm.exe is 6052580 bytes, but this one is only 957440 bytes.

I didn't notice. I've built it for release (`cargo build --release`). I guess that the previous executables were built as default with debug information.

**Comment by alank2** [comment]
Hi Iván,

 

My apologies for not having tested this yet – I’ll see if I can test it tonight for you!

 

Thanks,

 

Alan

**Comment by alank2** [comment]
Hi,

 

I need to recreate my test that I had to retest this; sorry for the delay.  I hope to get to it this weekend so I can give you feedback.

 

Thanks again,

 

Alan

 

 

From: Alan Kamrowski II ***@***.*** 
Sent: Monday, January 15, 2024 12:47 PM
To: 'ivanizag/iz-cpm' ***@***.***>; 'ivanizag/iz-cpm' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [ivanizag/iz-cpm] Compute File Size is incorrect (Issue #11)

 

Hi Iván,

 

My apologies for not having tested this yet – I’ll see if I can test it tonight for you!

 

Thanks,

 

Alan

**Comment by ivanizag** [comment]
Don't worry, there is no rush. We are doing this for fun.

**Comment by alank2** [comment]
Hi Iván,

>Don't worry, there is no rush. We are doing this for fun.

I agree!  Testing finished and it works perfectly now!  Good work.

Please let me know when a new release is up!

Thanks,

Alan

**Comment by alank2** [comment]
Hi Iván,

 

I found a couple more things that I hope are helpful:

 

(I’m using the test version you sent me, not anything new you’ve released)

 

#1 – the original iz-cpm, CTRL-H works fine in my application (it does a backspace, space, backspace).

In the new version, it shows ←[D instead.

Maybe there is some sort of terminal configuration that I need to do on the new one?

 

#2 – A difference in the logging (this is a great feature by the way):

OLD ONE: [[BDOS command 26: F_DMAOFF(ee90)]][[BDOS command 33: F_READRAND(ef1f)]][Read random record 58 into ee90][[=>01]]

NEW ONE: [BDOS command 26: F_DMAOFF(ee90)]][[BDOS command 33: F_READRAND(ef1f)]][Read radom record 58 into ee90][[=>00]]

 

I know this BDOS call fails and in the OLD iz-cpm, it correctly shows that with the =>01 response.  The new version shows =>00, but I know it fails.  This is a final partial sector write where I read the sector to see if it exists (it doesn’t).

 

#3 – An issue both versions have – they say read random when it is a write random.

[[BDOS command 26: F_DMAOFF(ef44)]][[BDOS command 34: F_WRITERAND(ef1f)]][Read random record 58 into ef44][[=>00]]

 

Thanks again!

 

Alan

**Comment by ivanizag** [comment]
Hi Alan, thanks for the reports. Let me go through them:

-1: I don't know if it ever changed. For adm3a emulation, I replace ^H with ESC ]D. To emulate the cursor left key. You can try to use that ANSI emulation that doesn't do any translation as I assume the host uses it. Try with --terminal ansi

-2: That was changed as I found a program working on my Kaypro and failing in iz-cpm because of this. See #6. CalcStart expects this not to fail. And the CP/M in KAypro looks like it is not reporting an error.

-3: Fixed. Thanks!

I still have the release pending.

**Comment by alank2** [comment]
Hi Iván,

 

#1 = Is there a way to make It default to ANSI (without using the command line option).

 

#2 – This is interesting.  I would have expected a failure to be returned.  I am guessing that you are returning a sector back filled with 0x1a?  I use this call on the final record being written to see if it exists so I can merge the current writes (a partial record) into it, so my code relies upon the error so it can make a sector with 0x1a. and then merge.  Your way seems to work though it bypasses my way.  I did check CP/M under SIMH and it returns an error as I would have expected however.  I also started a this on the vintage computing forum to see what others think (there are some pretty hard core cp/m guys there).  I do have a Kaypro I can dig out so I can dig that out and test on it as well to see if I can reproduce your experience

 

#3 – Awesome.

 

BTW, I found your –cpu option, that is fantastic too.

 

Thanks again,

 

Alan

**Comment by ivanizag** [comment]
I've looked further and it's interesting: The fix to the problem of #6 was not what I did. The issue was really the call to F_SIZE that happens just before that is actually fixed with your patch for this issue!

I just reverted the change for #6 and now it works. I hope to be able to do a windows release tonight.

**Comment by ivanizag** [comment]
I've finally released v.1.3.1 !
