### ISSUE TITLE
CP/M licensing

### ISSUE THREAD

**Issue by davidgiven** [ivanizag/iz-cpm#2]
I've got good news and bad news...

The bad news is that DR's CP/M isn't open source. It was semi-freed back in 2001 with a mostly-but-not-quite license (excerpted from http://www.gaby.de/cpm/license.html):

```
Let this email represent a right to use, distribute, modify, enhance and
otherwise make available in a nonexclusive manner the CP/M technology as
part of the "Unofficial CP/M Web Site" with its maintainers, developers and
community.
```

So, it can't be legally distributed anywhere other that www.gaby.de/cpm. It's very unlikely that anyone would be sued for distributing it, but it is a license violation and so will prevent distribution in, for example, Debian. (I've been looking into the licensing of CP/M software for a project of mine where I've been trying to produce a properly open source CP/M distribution, at http://github.com/davidgiven/cpmish.)

The good news is that ZSDOS and ZCPR1 are drop-in replacements and _are_ distributable. At least, they do to the best of my knowledge; licensing back then was a mess. But I'm pretty confident that ZCPR1 is public domain (but not subsequent versions) and ZSDOS is actually GPLd. I've got copies that have been patched to build with zmac at https://github.com/davidgiven/cpmish/tree/master/third_party/zcpr1 and https://github.com/davidgiven/cpmish/tree/master/third_party/zsdos if you want them.

**Comment by ivanizag** [comment]
I was trying to ignore somehow the issue. The my main purpose of this project is to learn how CP/M works, I wanted to use the original DR-DOS CPP.

But probably the time is due to acknowledge the issue. I think I just need a CCP replacement. I will try embedding ZCPR1 and probably add a command line switch to use a non-embedded CCP binary if available.

Thanks for the tip on ZCPR1 and the work on cpmish

**Comment by davidgiven** [comment]
Yeah, I don't think it's anything to practically worry about, but it will cause problems getting the package distributed. (Disclaimer: I actually have my own CP/M emulator for various projects, and I hate it, and I'd much rather use someone else's, so I have an interest in getting this accepted into Debian...)

**Comment by ivanizag** [comment]
Done. Most of it was just copying how it was done in cpmish.
