### ISSUE TITLE
Is there a chance to change the "double-ctrl-c" to a more "secure" key-combination?

### ISSUE THREAD

**Issue by guidol70** [ivanizag/iz-cpm#3]
Hi,
Thanks for the interesting emulator! :)
Is there a chance to get instructions how to get iz-cpm compiled under a ARM linux OS (armbian)?

When I try to cargo check/build I do get the error-message:

root@npi-neo2-23(192.168.6.23):/toshiba/iz-cpm-1.0# cargo check
error: failed to parse lock file at: /toshiba/iz-cpm-1.0/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`

Which dependencies do I need and how do I install them?

Kind Regards
Guido

**Comment by ivanizag** [comment]
I don't have a setup to test this right now, but I don't know why it would not work on linux ARM.

It may be this https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#less-conflict-prone-cargolock-format . What version of rust are you using? Can you delete `Cargo.lock` and try again?

**Comment by guidol70** [comment]
Deleting the Cargo.lock did the trick.
Sorry for that - Iam today a first time user of cargo/rustc ;)
On my NanoPi Neo2 with armbian Iam using the rust-version under armbian buster
( Linux npi-neo2-23 5.6.16-sunxi64 #trunk SMP Sun Jun 28 16:58:27 +03 2020 aarch64 GNU/Linux ):
 rustc  1.34.2+dfsg1-1

compile does now complete :)
-rwxrwxrwx 2 root root 10496048 Jul 25 13:23 iz-cpm

Around 10MB seems to be much bigger than the x86-linux-version or the Windows version.

Is there a chance to change the "double-ctrl-c" to a more "secure" key-combination?
Because when anyone in MBASIC does stop his program with Ctrl-C (and the computer did this get as double-ctrl-c) then the emulator quits and the BASIC program isnt saved.
Or how about a "Are you sure to quit?" :)

**Comment by ivanizag** [comment]
Changed to request confirmation:

``
iz-cpm https://github.com/ivanizag/iz-cpm
CP/M 2.2 Emulation
Press ctrl-c ctrl-c Y to return to host

A>
Press Y to exit iz-cpm. Any other key to continue.
```
