### ISSUE TITLE
Debian compile error

### ISSUE THREAD

**Issue by cavaughankirov** [ivanizag/iz-cpm#9]
Installing on Debian bullseye. Had to enable the sid repository in order to get a version of cargo that could compile. Nonetheless, getting the following error:

error: unknown `--json` option `future-incompat`

error: unknown `--json` option `future-incompat`
error: unknown `--json` option `future-incompat`

error: could not compile `ansi_term`
warning: build failed, waiting for other jobs to finish...
error: could not compile `unicode-width`
error: could not compile `libc`
error: unknown `--json` option `future-incompat`

error: could not compile `strsim`

**Comment by ivanizag** [comment]
Have you installed rust from the debian repositories or from https://www.rust-lang.org/tools/install ?

**Comment by cavaughankirov** [comment]
After enabling the sid repository I have been able to compile iz-cpm. Thanks!

**Comment by ivanizag** [comment]
Great
